### PR TITLE
Switch to it_IT locale

### LINKED ISSUE #106: Change the locale from it to it_IT
This will allow us to use the country specific locale for dirittodisapere and use the more general Italian locale for sites such as AskTheEU

### PR DESCRIPTION
**Pull request by lizconlan**
Closes #106 

I *think* this is it bar...
 - [ ] editing the config
 - [ ] update locale data (by running script, [pasted below](#issuecomment-272835935))

### CODE REVIEW

**Comment by garethrees** [comment]
> updating `PublicBody` and `PublicBodyCategory` to use the new locale

`PublicBodyHeading` is also `Translatable`. `User` also has a `locale` attribute, so check whether that will need updating too. Probably worth pasting the script/sql you're going to run here for a quick sanity check.

**Comment by lizconlan** [comment]
Proposed script:

```rb
PublicBody::Translation.where(:locale => "it").update_all(:locale => "it_IT")
PublicBodyHeading::Translation.where(:locale => "it").update_all(:locale => "it_IT")
PublicBodyCategory::Translation.where(:locale => "it").update_all(:locale => "it_IT")
User.where(:locale => "it").update_all(:locale => "it_IT")
```

**Comment by garethrees** [comment]
Turns out [`Comment` has a locale attribute](https://github.com/mysociety/alaveteli/blob/develop/app/models/comment.rb#L13) too! Don't know if its used. Scripts look fine.

**Comment by lizconlan** [comment]
(Script updated to include `Comment`)

**Comment by lizconlan** [comment]
In case of emergency \*ahem\* reverse script:

```rb
PublicBody::Translation.where(:locale => "it_IT").update_all(:locale => "it")
PublicBodyHeading::Translation.where(:locale => "it_IT").update_all(:locale => "it")
PublicBodyCategory::Translation.where(:locale => "it_IT").update_all(:locale => "it")
User.where(:locale => "it_IT").update_all(:locale => "it")
Comment.where(:locale => "it_IT").update_all(:locale => "it")
```

**Pull request merged**
