### PR TITLE
Changes to Chiedi/2

### PR DESCRIPTION
**Pull request by clacesarano**
- Green favicon
- Bigger logo
- DDS logo in the footer ("a project by...")
- Added the variable chied_light_green
- Buttons in light green
- Revised versions oh help pages ("about" and "requesting")
- Added more suggestions in the request page (new.html.erb)

### CODE REVIEW

**Comment by garethrees** [comment]
Thanks @clacesarano – I had to fix a couple of things, so merged outside of github:

https://github.com/mysociety/dirittodisapere-theme/compare/87b40335f824a9c5b1c22aa359be8f652471e2a8%5E...1361a48a9b6a9277c980a16323fb63c79e833d53

**Comment by garethrees** [comment]
Deployed :ship:

**Comment by clacesarano** [comment]
Thanks Gareth,
two questions:
1)I uploaded a bigger version of the logo but the size is the same in the end: is there a maximum for the size of the logo
2)I changed the logo ath the bottom (under "un progetto di") putting back the logo of Diritto Di Sapere. I can see it in the pull request but not in the final result. Why?

**Comment by garethrees** [comment]
> I uploaded a bigger version of the logo but the size is the same in the end: is there a maximum for the size of the logo

I think that's the maximum size without doing further work to the theme, yes. I think it looks good – any bigger might end up leaving a lot of wasted space before you get to the interesting request content.

> I changed the logo ath the bottom (under "un progetto di") putting back the logo of Diritto Di Sapere. I can see it in the pull request but not in the final result. Why?

I can't see this modification, so not quite sure where you can see it. Might be easier to just make the change again? Make sure you [sync your branch](https://help.github.com/desktop/guides/contributing/syncing-your-branch/) with the latest `master` branch so that your working copy has the latest updates.

**Pull request closed without merging**
